### ISSUE TITLE
Add tests for BankNote

### ISSUE THREAD

**Issue by bokherus** [OOP2018/coinpurse-cynic4018#12]
You haven't test BankNote for insert, withdraw, and getBalance as specified in the sheet yet.

**Comment by bokherus** [comment]
@cynic4018 You will need to complete this issue. Please fix it by Sunday. I did open an issue for others on this topic but somehow I forgot to open this issue for you. However, for next time please read the instructions carefully. Since I've open this issue for others so I'll be fair and give you the chance to get full score.

**Comment by cynic4018** [comment]
@bokherus lab2 ,I don't know where?

**Comment by cynic4018** [comment]
@bokherus  ok, I already test banknote in purseTest class. it's ok ,right ?
