### ISSUE TITLE
compareTo should be compare currency and so on..

### ISSUE THREAD

**Issue by taveratch** [OOP2018/coinpurse-cynic4018#14]
Please follow the instruction.
https://github.com/OOP2018/coinpurse-cynic4018/blob/6be530f90390033c464321b38130bdd446423960/src/coinpurse/Money.java#L36-L38

**Comment by cynic4018** [comment]
I'm already fixed in valuable class by extends comparaable<Valuable> and compareTo that use compare from ValueComparator , I think that good enough. All this it's ok right?
